# Server
server.port=8081

# Database MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# Ejecutar data.sql al iniciar la aplicación
#spring.sql.init.mode=always

# Esperar a que Hibernate cree/actualice las tablas antes de ejecutar data.sql
#spring.jpa.defer-datasource-initialization=true

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION:86400000}

# CORS
app.frontend-url=${APP_FRONTENDURL}

# Password recuperacion de OWNER
app.ownerPasswordRecovery=${OWNER_PASSWORD_RECOVERY}

# Schedule - tareas automaticas
app.scheduler.initial-delay=${SCHDULER_INITIAL_DELAY:30000}
app.shceduler.fixed-rate=${SCHEDULER_FIXED_RATE:60000}