package com.cfp.mapa.model.enums;

public enum TipoEspacio {
    AULA,
    BUFFET,
    OFICINA,
    SECRETARIA,

    TALLER,
    LABORATORIO,
    PATIO,

    BANIO_MASCULINO,
    BANIO_FEMENINO,
    BANIO_ACCESIBLE,
    BANIO_MIXTO,

    ENTRADA_PRINCIPAL_CFP,
    ENTRADA_PRINCIPAL_PREDIO,
    ENTRADA_SECUNDARIA,
    PUNTO_DE_PASO
}
